# Generated by Django 4.0.3 on 2022-03-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('test1', models.CharField(max_length=10)),
                ('test2', models.CharField(max_length=10)),
                ('test3', models.CharField(max_length=10)),
                ('test4', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
